services:
  devbox:
    image: "healthsamurai/aidboxone:edge"
    depends_on:
      - devbox-db
    ports:
      - 8080:8080
    links:
      - "devbox-db:database"
    env_file:
      - env_tests
    environment:
      AIDBOX_LICENSE: ${AIDBOX_LICENSE}
  devbox-db:
    image: healthsamurai/aidboxdb:14.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devbox
  devbox-healthcheck:
    image: curlimages/curl
    entrypoint: /bin/sleep 10000
    links:
      - devbox
    depends_on:
      - devbox
    healthcheck:
      test: curl --fail http://devbox:8080/__healthcheck || exit 1
      interval: 1s
      timeout: 20s
      retries: 100
  app:
    build:
      context: .
      args:
        PYTHON_VERSION: ${PYTHON:-3.11}
    command: ["pipenv", "run", "pytest"]
    depends_on:
      devbox-healthcheck:
        condition:
          service_healthy
    links:
     - devbox
    ports:
     - "8081:8081"
    volumes:
     - .:/app
