name: fhirpy

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: 3.8
          - python-version: 3.9
          - python-version: "3.10"
          - python-version: "3.11"
    env:
      PYTHON: ${{ matrix.python-version }}
      AIDBOX_LICENSE: ${{ secrets.AIDBOX_LICENSE}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: docker compose -f docker-compose.tests.yaml up --exit-code-from app app
    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v3
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     env_vars: PYTHON
    #     fail_ci_if_error: true
    #     files: ./coverage.xml
    #     flags: unittests
    #     name: codecov-umbrella
    #     verbose: true
